services:
  neo4j:
    image: neo4j:5.16
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/F9gsV3zmLpQ2xT"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_importd_file_use__neo4j__config: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.meta.*,apoc.*,gds.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.meta.*,apoc.*,gds.*"
    volumes:
      - ./data:/data

  neo4j_finance:
    image: neo4j:5.16
    container_name: neo4j_finance
    ports:
      - "7475:7474"   # Neo4j browser
      - "7688:7687"   # Bolt protocol
    environment:
      NEO4J_AUTH: "neo4j/F9gsV3zmLpQ2xT"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.meta.*,apoc.*,gds.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.meta.*,apoc.*,gds.*"
    volumes:
      - ./data_finance:/data
